abis:
  auction: ./abis/Auction.json
  auction_factory: ./abis/AuctionFactory.json
  erc20: ./abis/ERC20.json
  legacy_auction: ./abis/LegacyAuction.json
  legacy_auction_factory: ./abis/LegacyAuctionFactory.json
database:
  url: ${DATABASE_URL}
indexer:
  auction_batch_size: 10 # max length of array to use in get_logs per request
  log_level: INFO
  poll_interval: 10
pricing:
  quote_api_max_age_minutes: 20
networks:
  ethereum:
    chain_id: 1
    block_batch_size: 15000
    factories:
      - address: 0xCfA510188884F199fcC6e750764FAAbE6e56ec40
        start_block: 21835027
        type: legacy
    rpc_url: ${ETHEREUM_RPC_URL}
  base:
    chain_id: 8453
    block_batch_size: 100
    factories:
      - address: 0xCfA510188884F199fcC6e750764FAAbE6e56ec40
        start_block: 26314893
        type: legacy
    rpc_url: ${BASE_RPC_URL}
  berachain:
    chain_id: 80094
    block_batch_size: 100
    factories:
      - address: 0xCfA510188884F199fcC6e750764FAAbE6e56ec40
        start_block: 1070705
        type: legacy
    rpc_url: ${BERACHAIN_RPC_URL}
  arbitrum:
    chain_id: 42161
    block_batch_size: 100
    factories: [] # No factory deployed yet
    rpc_url: ${ARBITRUM_RPC_URL}
  local:
    chain_id: 31337
    block_batch_size: 100
    factories:
      - address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
        start_block: 57
        type: modern
      - address: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
        start_block: 57
        type: legacy
    rpc_url: http://localhost:8545
  optimism:
    chain_id: 10
    block_batch_size: 100
    factories: [] # No factory deployed yet
    rpc_url: ${OPTIMISM_RPC_URL}
  polygon:
    chain_id: 137
    block_batch_size: 100
    factories: [] # No factory deployed yet
    rpc_url: ${POLYGON_RPC_URL}
